### ISSUE TITLE
Using proxy with playwright+chromium causes a crash

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#484] opened 2024-08-30 14:58 UTC
Issue from Discord

![image (4)](https://github.com/user-attachments/assets/bae16883-f2ae-41fa-9f06-ff68e6c55572)
![image (6)](https://github.com/user-attachments/assets/0e9895df-8cf8-47ba-833b-8f1e14efe0cb)

**Comment by vdusek** [comment] 2024-09-25 14:29
I was not able to reproduce this one.

Code:
```python
import asyncio

from crawlee.playwright_crawler import PlaywrightCrawler, PlaywrightCrawlingContext
from crawlee.proxy_configuration import ProxyConfiguration


async def main() -> None:
    proxy_configuration = ProxyConfiguration(
        proxy_urls=[
            'http://auto:PASSWORD@proxy.apify.com:8000',
        ]
    )

    crawler = PlaywrightCrawler(
        max_requests_per_crawl=5,
        headless=False,
        browser_type='chromium',
        proxy_configuration=proxy_configuration,
        use_session_pool=True,
    )

    @crawler.router.default_handler
    async def default_handler(context: PlaywrightCrawlingContext) -> None:
        context.log.info(f'Processing {context.request.url} ...')
        data = {
            'url': context.request.url,
            'title': await context.page.title(),
        }
        await context.push_data(data)
        await context.enqueue_links()

    await crawler.run(['https://crawlee.dev'])


if __name__ == '__main__':
    asyncio.run(main())
```

Output:
```text
$ python run_issue_484.py 
[crawlee.playwright_crawler._playwright_crawler] INFO  Current request statistics:
┌───────────────────────────────┬──────────┐
│ requests_finished             │ 0        │
│ requests_failed               │ 0        │
│ retry_histogram               │ [0]      │
│ request_avg_failed_duration   │ None     │
│ request_avg_finished_duration │ None     │
│ requests_finished_per_minute  │ 0        │
│ requests_failed_per_minute    │ 0        │
│ request_total_duration        │ 0.0      │
│ requests_total                │ 0        │
│ crawler_runtime               │ 0.012318 │
└───────────────────────────────┴──────────┘
[crawlee._autoscaling.autoscaled_pool] INFO  current_concurrency = 0; desired_concurrency = 2; cpu = 0.0; mem = 0.0; event_loop = 0.0; client_info = 0.0
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev ...
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev/python/ ...
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev/docs/quick-start ...
[crawlee.playwright_crawler._playwright_crawler] INFO  The crawler has reached its limit of 3 requests per crawl. All ongoing requests have now completed. Total requests processed: 3. The crawler will now shut down.
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev/docs/examples ...
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev/api/core ...
[crawlee.playwright_crawler._playwright_crawler] INFO  Processing https://crawlee.dev/api/core/changelog ...
[crawlee._autoscaling.autoscaled_pool] INFO  Waiting for remaining tasks to finish
[crawlee.playwright_crawler._playwright_crawler] INFO  Final request statistics:
┌───────────────────────────────┬───────────┐
│ requests_finished             │ 6         │
│ requests_failed               │ 0         │
│ retry_histogram               │ [6]       │
│ request_avg_failed_duration   │ None      │
│ request_avg_finished_duration │ 11.333144 │
│ requests_finished_per_minute  │ 10        │
│ requests_failed_per_minute    │ 0         │
│ request_total_duration        │ 67.998864 │
│ requests_total                │ 6         │
│ crawler_runtime               │ 34.560767 │
└───────────────────────────────┴───────────┘
```

Closing.

**Closed by vdusek** 2024-09-25 14:29 UTC
Labels: bug, t-tooling
