### ISSUE TITLE
Implement `KeyValueStore.get_public_url`

### ISSUE THREAD

**Issue by janbuchar** [apify/crawlee-python#514] opened 2024-09-10 16:09 UTC
- https://github.com/apify/crawlee/blob/master/packages/core/src/storages/key_value_store.ts#L457-L463 could serve as inspiration
  - we should consider also making this a method of the kv-store resource client and implementing it separately for memory storage and for platform storage in SDK
- when this is done, update the deployment/apify-platform docs page (there is commented out doc for this feature)

**Comment by ravi-hash** [comment] 2024-10-02 15:07
Hey will you assign this issue to me

**Comment by naaa760** [comment] 2024-10-03 02:54
Hello! @janbuchar  :)


I think we need to add some checks and better handling of errors. First, we should make sure that the key and **storeName** are valid before trying to generate a URL. Depending on whether we’re using memory storage or platform storage, we handle them differently: for memory storage, we can return a local URL **(like localhost)**, but we need to be aware that this might not be publicly accessible. For platform storage, we should create a URL that fits the platform’s format. If the **storageType** is unknown, we throw an error so the issue is clear. Wrapping everything in try-catch helps us catch any unexpected problems and log useful error messages, making the code more reliable.

**Comment by janbuchar** [comment] 2024-10-03 08:41
Hello @ravi-hash and @naaa760, we will accept a PR from whomever finishes it first, no need to have it assigned first.

**Closed** 2024-10-22 08:10 UTC
Labels: enhancement, t-tooling, hacktoberfest
